# Streamlit config — tema escuro de fallback (caso CSS não carregue)
[theme]
base = "dark"
primaryColor = "#A38ADB"
backgroundColor = "#05080A"
secondaryBackgroundColor = "#101B1F"
textColor = "#EAF2F2"
font = "sans serif"

[server]
headless = true
runOnSave = false
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false
